apiVersion: v1
kind: Service
metadata:
  name: vehicle-sales-api-service
  namespace: tech-challenge
  labels:
    app: vehicle-sales-api
spec:
  type: LoadBalancer
  selector:
    app: vehicle-sales-api
  ports:
    - name: http
      protocol: TCP
      port: 8001
      targetPort: 8001
